### PR TITLE
WIP Webpack v4.0.0 support

### PR DESCRIPTION
**Pull request by Graham42**
This is a continution of https://github.com/jantimon/html-webpack-plugin/pull/823 

Some tests still failing, actively working on this.

### CODE REVIEW

**Comment by Graham42** [comment]
This is going to need https://github.com/webpack-contrib/extract-text-webpack-plugin/pull/707 to land first.

I'm locally building and linking in that PR as my `extract-text-webpack-plugin` dependency.

**Comment by TheLarkInn** [comment]
@Graham42 this is incredible work. I'll assign the right folks to take a look at this briefly for final reviews. 

cc @evilebottnawi @michael-ciniawsky @sokra 

My assumptions that we publish this under `@webpack-contrib/html-webpack-plugin`. Any objections?

File: index.js [hunk 1]
```diff
@@ -42,6 +42,20 @@ HtmlWebpackPlugin.prototype.apply = function (compiler) {
     this.options.filename = path.relative(compiler.options.output.path, filename);
   }
 
+  // setup hooks for webpack 4
+  if (compiler.hooks && compiler.hooks.compilation) {
```
Comment (ooflorent) [inline index.js]: Testing for `compiler.hooks` should be enough.

File: index.js [hunk 2]
```diff
@@ -640,16 +667,48 @@ HtmlWebpackPlugin.prototype.getAssetFiles = function (assets) {
...
+        compilation.errors.push(
+          new Error('No hook found for ' + eventName)
+        );
+      }
+
+      return compilation.hooks[ccEventName].promise(pluginArgs);
+    };
+  } else {
+    // Before Webpack 4
+    var promisedApplyPluginsAsyncWaterfall = Promise.promisify(
```
Comment (ooflorent) [inline index.js]: I’m not a big fan of `promisify` because it is installed on `Promise` and looks like a builtin.

File: lib/chunksorter.js [hunk 3]
```diff
@@ -37,22 +41,52 @@ module.exports.dependency = function (chunks) {
...
-        // If the parent chunk does not exist (e.g. because of an excluded chunk)
-        // we ignore that parent
-        if (parentChunk) {
-          edges.push([parentChunk, chunk]);
-        }
+  if (chunkGroups) {
+    // Add an edge for each parent (parent -> child)
+    edges = chunkGroups.reduce(function (result, chunkGroup) {
+      return result.concat(
+        chunkGroup.getParents().map(function (parentGroup) {
```
Comment (ooflorent) [inline lib/chunksorter.js]: `Array.from(chunkGroup.parentsIterable, fn)` drains the iterable only once.

File: index.js (hunk 2 above)
Comment (niieani) [reply index.js]: Depending on the target, one could use the built-in `promisify`: http://2ality.com/2017/05/util-promisify.html

Comment (Graham42) [reply index.js]: Fair, but I don't think it's relevant to this PR. I just reformatted this line. Can look at this in a separate issue?

For target, this plugin supports back to webpack 1, and from the `.travis.yml` looks like node target is 4. So can't use the built-in `promisify`

**Comment by evilebottnawi** [comment]
Also if it still impossible let's publish under `@webpack-contrib/html-webpack-plugin`, but we should notify users (how?)

**Comment by Graham42** [comment]
From the previous thread: https://github.com/jantimon/html-webpack-plugin/pull/823#issuecomment-365070707
> jantimon is in Asia for work right now until first week of March. We've forked html-webpack-plugin for now to have the PR sent against there just to ensure people can actually have a chance to test and use this package prior to v4

`@webpack-contrib/html-webpack-plugin` sounds good. This is just to give people beta access to test things out.

**Comment by evilebottnawi** [comment]
@Graham42 :+1: What about migrate in `@webpack-contrib/html-webpack-plugin` in future?

File: lib/chunksorter.js (hunk 3 above)
Comment (Graham42) [reply lib/chunksorter.js]: I'm not really familiar with iterables, could you elaborate please?

**Comment by michael-ciniawsky** [comment]
Just as a side note https://github.com/webpack-contrib/extract-text-webpack-plugin/releases/tag/v4.0.0-alpha.0 (EWTP v4.0.0 (`webpack >= v4.0.0` Support))

@evilebottnawi It's just extra noise the release a different package in any case, if there is no way around it sure just `@webpack-contrib/html-webpack-plugin` then :)

**Comment by Graham42** [comment]
Just trying to understand the iterable comment above.

**Comment by Graham42** [comment]
btw tests are green! :tada:  https://travis-ci.org/Graham42/html-webpack-plugin/

**Comment by andriijas** [comment]
it would be unfortunate with 2 packages in npm. But its even more unfortune to be dependent on one maintainer. 

Is he totally of the grid or can he add access to his repo to someone for the time being and then discussions of how to handle an eventual move could be done later.

**Comment by michael-ciniawsky** [comment]
> Is he totally of the grid or can he add access to his repo to someone for the time being and then discussions of how to handle an eventual move could be done later.

Yeah that would be the ideal way/case :)

File: index.js (hunk 2 above)
Comment (TheLarkInn) [reply index.js]: Yeah we can get back in and look at alternatives once we've gotten the initial out

**Comment by TheLarkInn** [comment]
GREEN TESTS!!!!!

**Comment by michael-ciniawsky** [comment]
We need to clarify the future maintenance and if republishing under `@webpack-contrib/html-webpack-plugin` is (definitely) the right thing to do. It would really be better if avoidable imho. And licensing if we do so ? (still needs the JSF license then ?) cc @d3viant0ne

**Comment by probablyup** [comment]
@TheLarkInn can we go ahead and publish a beta version under @webpack-contrib, just to test things?

**Comment by ekulabuhov** [comment]
Add this line to your package.json, to install the package from the branch: 
"html-webpack-plugin": "Graham42/html-webpack-plugin#feat/webpack-4"

**Comment by probablyup** [comment]
@ekulabuhov that works, ty

**Comment by TheLarkInn** [comment]
Yes we should publish this under @webpack-contrib/html-webpack-plugin. Are
we good to go here?

**Comment by TheLarkInn** [comment]
@michael-ciniawsky @d3viant0ne I think since this would be alpha/beta, we can make the hard requirement to go full release be having the licensing at the least.

**Comment by Graham42** [comment]
Good from my end

**Comment by TheLarkInn** [comment]
Alright @Graham42 thank you so much for this. The @webpack-contrib/admin-team are just discussing some housekeeping stuff before we merge and release. This is green light though.

**Comment by TheLarkInn** [comment]
@graham42 thank you so much for this work. To not separate the ecosystems, we are going to have this merged and point people to this commit as a point of install. From there we will give time for @jantimon to get back from his work orders to take time on this in hopes of merging back into upstream.

**Comment by chyzwar** [comment]
is there is a plan to move things to scoped packages @webpack-contrib and @webpack ?

**Comment by TheLarkInn** [comment]
@chyzwar, currently @jantimon is out of the country, and we want to _wait until he is back_ before we can merge it back upstream and have him publish a fix. There are changes upstream that he would like to accommodate. This is mean to take some pressure off of him and get people testing and reporting any issues from this plugin, etc.

**Comment by damianobarbati** [comment]
@TheLarkInn what is the correct package to add into `package.json` to have `html-webpack-plugin` working with `webpack@4.0.0-beta.2` without the tapable/AsyncSeriesHook errors then? 🙏🏻

Tried:
```
"html-webpack-plugin": "Graham42/html-webpack-plugin#feat/webpack-4",
```
With no luck.

**Comment by damianobarbati** [comment]
@mkhazov thanks for helping, that's what I'm using right now but it doesn't work.
I get:
```
ERROR in   TypeError: __webpack_require__(...) is not a function
  - es6.regexp.replace.js?:2 eval
    [.]/[core-js]/modules/es6.regexp.replace.js?:2:90
```
I wrongly reported this bug to `webpack` here https://github.com/webpack/webpack/issues/6544

Here a simple repro: https://github.com/damianobarbati/yarsk

**Comment by Graham42** [comment]
@damianobarbati can you open a separate bug for this please

**Comment by damianobarbati** [comment]
Sure @Graham42, here it is: https://github.com/webpack-contrib/html-webpack-plugin/issues/12

**Comment by kcolton** [comment]
@Graham42 @TheLarkInn This is great work. Really happy to see such a proactive approach and effort to have Plugins ready for Webpack 4. Think the new plugin architecture is fantastic and should help both facilitate new plugin development and encourage collaboration on plugins that overlap in functionality 👍 

I'm running `webpack-contrib/html-webpack-plugin` and will give it a thorough shakedown in different use cases and report any findings. 

Any areas of docs that need revising for this (or Webpack 4 in general actually)? Or other plugins that need some assistance? Webpack 4 is a great step forward and happy to contribute.

Going through the big ones setting up a Webpack 4/Babel 7 shakedown environment, which is how I landed here and grateful for everyone's effort on this.

**Comment by SteveByerly** [comment]
I setup a new project with this version of the plugin and get the following error:

`TypeError: SyncWaterfallHook is not a constructor`

Seems like installing [webpack/tapable](webpack/tapable) fixes the error for now `npm i -D tapable`
though I now get deprecation warnines
```
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
```

**Comment by thescientist13** [comment]
@SteveByerly 
I am getting this as well.  Do you think it would be worth opening a new issue just for it?

cc: @devlab2425

**Comment by dfederm** [comment]
I'm trying to use:
```
"html-webpack-plugin": "webpack-contrib/html-webpack-plugin",
```

But it seems to be running tests when trying to install, and the tests fail due to Windows vs Unix line-endings.

One of the more decipherable test failures:
```
20 error prepareGitDep 4) HtmlWebpackPlugin Examples javascript example
20 error prepareGitDep   Message:
20 error prepareGitDep     Text does not match, please review the diff below.
20 error prepareGitDep     Index:
20 error prepareGitDep     ===================================================================
20 error prepareGitDep     ---
20 error prepareGitDep     +++
20 error prepareGitDep     @@ -43,9 +43,9 @@
20 error prepareGitDep      /******/ ([
20 error prepareGitDep      /* 0 */
20 error prepareGitDep      /***/ (function(module, exports, __webpack_require__) {
20 error prepareGitDep
20 error prepareGitDep     -	eval("__webpack_require__(1);\n\nvar universal = __webpack_require__(5);\nvar h1 = document.createElement('h1');\nh1.innerHTML = universal();\n\ndocument.body.appendChild(h1);\n\n\n//////////////////\n// WEBPACK FOOTER\n// ./example.js\n// module id = 0\n// module chunks = 0\n//# sourceURL=webpack:///./example.js?");
20 error prepareGitDep     +	eval("__webpack_require__(1);\r\n\r\nvar universal = __webpack_require__(5);\r\nvar h1 = document.createElement('h1');\r\nh1.innerHTML = universal();\r\n\r\ndocument.body.appendChild(h1);\r\n\n\n//////////////////\n// WEBPACK FOOTER\n// ./example.js\n// module id = 0\n// module chunks = 0\n//# sourceURL=webpack:///./example.js?");
```

Until this is merged upstream, can a temporary package be pushed or remove the `prepare` from package.json?

**Comment by thescientist13** [comment]
@dfederm 
This seems to be related to the changes made after the merge of the webpack v4 compat branch.  YMMV (per my issue in #13), but you could try using the hash of the v4 compat branch - [`a8a8c2b6ea496c257fd6f501db3a06a51fa03e1e`](https://github.com/webpack-contrib/html-webpack-plugin/commit/a8a8c2b6ea496c257fd6f501db3a06a51fa03e1e)

**Comment by dfederm** [comment]
@thescientist13 Thanks! I was able to `npm i` at least now, but looks like I'm hitting the same issue you are with `SyncWaterfallHook`. I'll watch that issue over there.
